# mysql.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-db-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: drupal
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: drupal-db-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-db-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
---
apiVersion: apps/v1
kind: Service
metadata:
  name: drupal-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: drupal-mysql
