# drupal.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: drupal:10
          ports:
            - containerPort: 80
          env:
            - name: DRUPAL_DB_HOST
              value: drupal-mysql
            - name: DRUPAL_DB_NAME
              value: drupal
            - name: DRUPAL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: drupal-db-secret
                  key: mysql-user
            - name: DRUPAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-db-secret
                  key: mysql-password
---
apiVersion: apps/v1
kind: Service
metadata:
  name: drupal
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - port: 80
      targetPort: 80
