<<<<<<< HEAD
=======

>>>>>>> b5f276b9686c2f2c1551f757a6a743edb2894115
apiVersion: netwroking.k8s.io/v1
kind: NetworkingPolicy
metadata:
  name: allow-backend-to-frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: mysql-service
    ports:
    - protocol: TCP
      port: 8080
