<<<<<<< HEAD
apiVersion: netwroking.k8s.io/v1
kind: NetworkingPolicy
metadata:
  name: allow-backend-to-frontend
=======
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-frontend
  namespace: default   # change if you are using another namespace
>>>>>>> main
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
<<<<<<< HEAD
          app: backend
    ports:
    - protocol: TCP
      port: 8080
=======
          app: mysql-service
    ports:
    - protocol: TCP
      port: 8080
# 
>>>>>>> main
