apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: dXNlcg==        # "user" in base64
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=     #password
  mysql-database: bXlkYg==                     # "mydb" in base64